# Generated by Django 4.0.6 on 2024-05-04 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
                ('teams', models.JSONField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=250)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport_type', models.CharField(max_length=250)),
                ('fullname', models.CharField(max_length=250)),
                ('ahortname', models.CharField(max_length=250)),
                ('group', models.CharField(max_length=3)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=50)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('event', models.JSONField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match')),
            ],
        ),
    ]
