# Generated by Django 4.0.6 on 2024-05-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ahortname_team_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
